### PR TITLE
login.php updated

### PR DESCRIPTION
**Pull request by zubayertahmid**
The Log In Authentication system has been updated in the newly designed frontend.

### CODE REVIEW

**Review by rr-uchchash360 — APPROVED** [review]

**Review by rr-uchchash360 — APPROVED** [review]

**Review by rr-uchchash360 — APPROVED** [review]

**Comment by zubayertahmid** [comment]
Mara kha

**Review by rr-uchchash360 — APPROVED** [review]

**Review by rr-uchchash360 — APPROVED** [review]

**Review by rr-uchchash360 — APPROVED** [review]

**Review by rr-uchchash360 — APPROVED** [review]

**Review by rr-uchchash360 — APPROVED** [review]

**Review by rr-uchchash360 — APPROVED** [review]

**Review by rr-uchchash360 — APPROVED** [review]

**Comment by rr-uchchash360** [comment]
Closed for testing purposes.

**Review by rr-uchchash360 — COMMENTED** [review]
Accepted

**Review by rr-uchchash360 — COMMENTED** [review]
added

**Pull request closed without merging**
